spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qrxy_user
    username: qrxy_user
    password: qrxy_user
  liquibase:
    change-log: classpath:db/changelog/master.xml

auth0:
  issuer: https://jamesngyz.auth0.com/
  apiAudience: https://test.qurrenxy.com